### ISSUE TITLE
Remove automatic map selection feature

### ISSUE THREAD

**Issue by NaughtyChas** [CloneWith/osu#19] opened 2024-08-05 17:47 UTC
In EX & Board screen, boxes will be automatically picked / banned when song information has updated through ipc.

Remove this for better stability.

**Comment by CloneWith** [comment] 2024-08-06 09:35
I've just removed the automatic selection feature for Board view.

Seemingly this goes fine with the EX Stage view, so I'm closing this issue.

**Comment by CloneWith** [comment] 2024-08-08 15:01
The test match revealed the issue again, temporarily reopening.

**Comment by cdwcgt** [comment] 2024-08-10 17:12
所以可能的问题是
我们需不需要这个功能
基于gameplay已经不在这里实现，我们还是否需要ipc来获取beatmap

最好明确一下

**Comment by NaughtyChas** [comment] 2024-08-10 17:19
> 所以可能的问题是 我们需不需要这个功能 基于gameplay已经不在这里实现，我们还是否需要ipc来获取beatmap
> 
> 最好明确一下

大概率是不需要了

经过测试赛发现这个功能会自动向下一张被选的图添加状态，而被添加的状态不会根据逻辑自动轮换。也就是说，如果使用ipc自动获取beatmap来做选择会导致所有图施加同一个效果 （*测试下来好像都是Red Pick*）。手动设定格子后，自动选图会覆盖刚才手动设定好的正确状态。

由于我们删除了右边按钮的轮换逻辑，因此这里也大概率是出现问题的

从导播的角度来看，**除非能够将下一张图自动轮换逻辑重新写好，建议还是移除这个功能**。

选图/Ban图轮换逻辑可以来 [这里](https://offfc.github.io/docs/handbook/#6-2-%E6%AF%94%E8%B5%9B%E6%B5%81%E7%A8%8B) 参考一下。

**Comment by CloneWith** [comment] 2024-08-10 23:32
> 我们需不需要这个功能

No need. Compared to manually switching, we are unsure about these parts:

- Whether or not all states of a block is overriden by IPC (even we've chosen to store them separately)
- If so, whether controllers can *quickly* restore the last correct of a block (especially with two teams of traps, in the worst scenario)

This feature will *most probably* mess the whole board up, enforcing us staffs to inhale large amounts of smoke during the normal match, not to mention we know little about this.

---

不需要（激寒。与手动选图相比，自动选图的行为有不确定性：

- 是否会清除格子已有的所有状态（即使我们把不同状态分开存储了）
- 发生此情况后，导播能否*迅速*将格子恢复到正确的状态（最坏的情况是，需要重新布置保图+2个陷阱）

可以想见，*多数情况*下这个功能会让棋盘阿米诺斯，强迫全体staff在直播间吸芙蓉王，更不用说我们对一得阁拉米所知甚少了。

**Comment by CloneWith** [comment] 2024-08-19 15:43
Have just:

- Add token verification for Board view maps (blocked automatic actions)
- Allow for EX automatic map selecting (we use an individual list for this)
- Unchanged for Mappool view maps

We can have a test sometime and then close the issue when everything about this goes as intended.

**Comment by NaughtyChas** [comment] 2024-08-20 08:23
Pinging @CloneWith for update on this issue.

Tested and everything is looking good, changing map in the matchroom will no longer trigger the automatic map-selection feature in lazer.

I believe that the automatic map-selection feature in EX Screen is intended to left in the code, however the default status of the selected map is incorrect. It uses a status similar to "Red Pick" in board screen as default:

|this unknown status|Red win status|
|:-:|:-:|
|![image](https://github.com/user-attachments/assets/2acf2315-24a3-4db1-9ca1-533062145e0b)|![image](https://github.com/user-attachments/assets/b3f9fb66-b25c-49ff-9e99-97cc4c0379ce)|

When "Pick" is selected on the control panel, applied status will be correct when performing auto-selection. This bug can be recreated by following these steps:

1. Do a fresh launch of the lazer
2. Go straight into EX screen, without selecting status on the control panel
3. Change the map in the match room to trigger automatic map selection

---

Setting the default status to "Pick" once we enter the EX screen should be a viable solution.

**Comment by CloneWith** [comment] 2024-08-21 16:53
> It uses a status similar to "Red Pick" in board screen as default.

Yes it's true, since in all views using `BeatmapChoice`, it starts with a "Red Pick".

Some solutions I suppose:

- [ ] Set the default button status (-> Neutral Pick)
- [ ] Rule out illegal choices (e.g. Pick with colors in this case)

**Comment by CloneWith** [comment] 2024-08-21 17:10
For now much of the issue should be complete.
If everything is OK then this can be closed as completed.

**Comment by CloneWith** [comment] 2024-09-14 23:08
测？等回

**Closed** 2024-09-15 10:03 UTC
Labels: bug, area:Board, priority:1, size:Small, area:Components

**Comment by NaughtyChas** [comment] 2024-09-16 07:22
New issue where
Seems this problem have not fixed for the new intro for map picks. Do you like Smoke team picked?
